Entire database connection is established as per the spring framework…
Progressive-Learning-Platform/plpTool-prototype pull request #104
Opened 2017-10-10 00:46 UTC by mjadhav1

…. Error message will be shown if the database is not configured.
I have changed the workflow of database connectivity. This is a major change. Please review it and suggest if any changes needed.

2017-10-10 00:51 UTC, mjadhav1 commented
You will get the database credentials in the **spring-datasource.xml** file.

2017-10-11 00:29 UTC, tobielf requested changes
1. Do we need to change from `Customer` to `customer`? I saw a lot of files only change on this. Try to keep the changes as minimal as possible. 
2. In your java code, unify your indentation; currently, your code is mixing space and tab.
3. Add the comment to all newly added code.

2017-10-11 02:37 UTC, mjadhav1 commented
@tobielf for 2. Can you tell me which java file has mixing of tabs and space? 
for 3. I have already added comments to the new code. Please check UserController.java, UserService.java, UserDAO.java

2017-10-11 04:11 UTC, mjadhav1 commented
@tobielf For 1. I have reverted the bower_components folder with the master. Now everything is back to the "Customer" from "customer". Please review it and let me know.

2017-10-16 10:20 UTC, tobielf reviewed
This protect method, should not be checkDatabaseConnection() and invoke at the start-up. Instead, you should handle the AJAX return value, like in  `plpController.js`, line 23, the response contains the error message, and alert to the user the detailed message so that it can be generalized. If there is no MySQL, warning on: configure a MySQL. If there is no DB named plp_db, warning on creating a DB. If there is no `user_info` table, warning on this type error. Error message needs provide enough, detail information, and the checking should only happen when an error occurred. 

In your current implementation, this function will invoke every time when the page is ready, which will impact the performance when the system is fine.

2017-10-16 10:20 UTC, tobielf commented on src/main/java/edu/asu/plp/controller/UserController.java
> +        return principal;
Tab indent here.

2017-10-16 10:20 UTC, tobielf commented on src/main/java/edu/asu/plp/controller/UserController.java
> +    public boolean checkDBConnection() {
Tab indent here.

2017-10-16 10:20 UTC, tobielf commented on src/main/java/edu/asu/plp/service/UserService.java
> +        return userDAO.saveUser(user);
Tab indent here.

2017-10-16 10:20 UTC, tobielf commented on src/main/java/edu/asu/plp/user/dao/impl/JdbcUserDAO.java
> +public class JdbcUserDAO implements UserDAO {
Comment your code.

2017-10-16 10:20 UTC, tobielf commented on target/classes/static/JS/plpController.js
> +	var checkDatabaseConnection = function () {
Check your indent.

2018-02-19 17:57 UTC, tobielf approved these changes

2018-02-19 18:22 UTC, merged