Refactor shirish
Progressive-Learning-Platform/plpTool-prototype pull request #98
Opened 2017-09-24 00:02 UTC by sschava1

I have added the comments to the classes so please provide feedback regarding the same. Also, please review the new gitignore files. I am not sure if @tobielf  deleted these files in master while merging the WebPLP branch and that is the reason it is not present in master. Since, I branched from master before WebPLP was merged to it, that could be the reason for the existence of these files. If that is the case, please let me know, and I will delete the files and issue a new pull request.
In any case, I did not intend to create these files.

Please note, that I have merged all the changes from master to refactor-shirish branch before issuing this pull request.

2017-09-24 21:04 UTC, tobielf requested changes
I also found an improper error handling when the request address is invalid in PLPAddressBus.java line 122. I will create an issue for this problem.

2017-09-24 21:04 UTC, tobielf commented on src/main/java/edu/asu/plp/tool/backend/isa/events/MemWatchResponseEvent.java
> +	 * getter for success flag
Method `isSuccess` use for indicating the result of memory watch request event. So, the comment getter for success flag won't help the user to understand it. Check how memory watch request been sent out and how the response been handled. E.g. in the handling code (WatchWindow.java line:313).
```
		if (!e.isSuccess())
			return;
```

2017-09-24 21:04 UTC, tobielf commented on src/main/java/edu/asu/plp/tool/backend/isa/events/MemWatchResponseEvent.java
> +	 * getter for property of the memory at particular address
Getter for the reference of the memory object at particular address.

2017-09-24 21:04 UTC, tobielf commented on src/main/java/edu/asu/plp/tool/backend/isa/events/MemWatchResponseEvent.java
> +	 * @return
Indicate the return value, like `@return a valid address when the watch request succeed, otherwise the address is invalid`

2017-09-28 17:15 UTC, sschava1 commented
I have committed the requested changes. Please review and accept my pull request.

2017-10-02 23:37 UTC, tobielf approved these changes

2017-10-03 00:01 UTC, tobielf commented
@sschava1 You can merge your branch now.

2017-10-03 00:41 UTC, merged